---
- hosts: all
  become: yes

  tasks:
    - name: Update packages
      yum:
        name: "*"
        state: latest

    - name: Install Convert2RHEL
      yum:
        name: https://github.com/oamg/convert2rhel/releases/download/v0.16/convert2rhel-0.16-1.el7.noarch.rpm
        state: present
    - name: Executing Convertion
      shell: convert2rhel --auto-attach --username=NazGarBX --password=Inspir@2020 -y
...
