---
- hosts: all
  become: yes
  tasks:
    - name: Update packages
      yum:
        name: "*"
        state: latest
    - name: Install Convert2RHEL
      yum:
        name: convert2rhel
        state: present
    - name: Executing Convertion
      shell: convert2rhel --auto-attach --username=ngarzon@inspirait.com --password=Inspir@2020 -y
...
